# Generated by Django 4.2.1 on 2023-05-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=200, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "course_link",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("agency", models.TextField(blank=True, max_length=10, null=True)),
                ("timestamp", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, max_length=100, null=True)),
                ("name_cf", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_cf",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("school_cf", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "prices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.TextField(blank=True, max_length=50, null=True)),
                ("agency", models.TextField(blank=True, max_length=10, null=True)),
                ("website_link", models.URLField(blank=True, null=True)),
                ("country", models.TextField(blank=True, max_length=100, null=True)),
                ("city", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "neighbourhood",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("vibe_fun", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "vibe_family",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "vibe_backpack",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "vibe_quiet",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "vibe_serious",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("price_1", models.BooleanField(blank=True, default=False, null=True)),
                ("price_2", models.BooleanField(blank=True, default=True, null=True)),
                ("price_3", models.BooleanField(blank=True, default=False, null=True)),
                ("size_1", models.BooleanField(blank=True, default=False, null=True)),
                ("size_2", models.BooleanField(blank=True, default=True, null=True)),
                ("size_3", models.BooleanField(blank=True, default=False, null=True)),
                ("age_1", models.BooleanField(blank=True, default=True, null=True)),
                ("age_2", models.BooleanField(blank=True, default=False, null=True)),
                ("age_3", models.BooleanField(blank=True, default=False, null=True)),
                ("age_4", models.BooleanField(blank=True, default=False, null=True)),
                ("pro_1", models.BooleanField(blank=True, default=False, null=True)),
                ("pro_2", models.BooleanField(blank=True, default=True, null=True)),
                ("pro_3", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "next_day_book",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("beach", models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                "db_table": "schools",
                "managed": True,
            },
        ),
    ]
