# Generated by Django 4.2.1 on 2023-06-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="description",
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="tagline",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
