# Generated by Django 4.2.1 on 2023-06-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_schools_description_schools_tagline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prices",
            options={"managed": True},
        ),
    ]
