# Generated by Django 4.2.1 on 2023-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_prices_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prices",
            name="location_cf",
        ),
        migrations.RemoveField(
            model_name="prices",
            name="name_cf",
        ),
        migrations.RemoveField(
            model_name="prices",
            name="school_cf",
        ),
        migrations.AddField(
            model_name="prices",
            name="school",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="id",
            field=models.AutoField(
                auto_created=True, db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="school_name",
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
