# Generated by Django 4.2.1 on 2023-06-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_prices_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="prices",
            name="school_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.schools",
            ),
        ),
        migrations.AlterField(
            model_name="prices",
            name="school",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
