# Generated by Django 4.2.1 on 2023-06-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_prices_school_id_alter_prices_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prices",
            name="school_id",
        ),
    ]
