# Generated by Django 4.2.1 on 2023-06-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_prices_school_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="prices",
            name="schools_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.schools",
            ),
        ),
    ]
