# Generated by Django 4.2.1 on 2023-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_prices_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(blank=True, max_length=200, null=True)),
                ("last_name", models.TextField(blank=True, max_length=200, null=True)),
                ("course", models.TextField(blank=True, max_length=200, null=True)),
                ("diveschool", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "date_of_birth",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "date_of_book",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("email", models.TextField(blank=True, max_length=200, null=True)),
                ("comment", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "bookings",
                "db_table": "bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="prices",
            options={"managed": True, "verbose_name_plural": "prices"},
        ),
        migrations.AlterModelOptions(
            name="schools",
            options={"managed": True, "verbose_name_plural": "schools"},
        ),
    ]
