# Generated by Django 4.2.1 on 2023-07-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_booking_options_alter_booking_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deniedfor",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
