# Generated by Django 4.2.1 on 2023-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_booking_deniedfor"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="denied",
            field=models.BooleanField(default=False),
        ),
    ]
