# Generated by Django 4.2.1 on 2023-07-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_booking_denied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="agency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="neighbourhood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="school_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
