# Generated by Django 4.2.1 on 2023-07-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_booking_comment_alter_booking_course_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="prices",
            new_name="Courses",
        ),
    ]
