# Generated by Django 4.2.1 on 2023-07-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_rename_prices_courses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"managed": True, "verbose_name_plural": "Courses"},
        ),
    ]
