# Generated by Django 4.2.1 on 2023-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_courses_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date_booked",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
